/**
 * The permission matrix a restaurant starts with — 13 roles against 25 permissions.
 *
 * It lives here rather than in the route because two things need it: the RBAC screen,
 * which lets an owner edit it, and the middleware that enforces it on every request.
 * Before that middleware existed this grid was only ever displayed, and the panel's own
 * PermissionGate hid buttons in the browser while the endpoints stayed open to anyone
 * signed in.
 */
export const DEFAULT_PERMISSIONS: Record<string, Record<string, boolean>> = {
  owner:        { view_orders: true, edit_orders: true, cancel_orders: true, refund_orders: true, add_menu: true, edit_pricing: true, delete_menu: true, hide_menu: true, view_wallet: true, view_settlements: true, view_reports: true, add_staff: true, remove_staff: true, edit_salary: true, edit_stock: true, approve_purchase: true, create_campaigns: true, send_promotions: true, qr_controls: true, nfc_controls: true, printer_settings: true, time_based_access: true, device_based_access: true, branch_wise_access: true, approval_workflows: true, activity_tracking: true },
  manager:      { view_orders: true, edit_orders: true, cancel_orders: true, refund_orders: false, add_menu: true, edit_pricing: true, delete_menu: false, hide_menu: true, view_wallet: true, view_settlements: false, view_reports: true, add_staff: true, remove_staff: false, edit_salary: false, edit_stock: true, approve_purchase: true, create_campaigns: true, send_promotions: true, qr_controls: true, nfc_controls: false, printer_settings: true, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: true },
  cashier:      { view_orders: true, edit_orders: false, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: false, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: false, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: true, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  waiter:       { view_orders: true, edit_orders: false, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: false, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: false, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: false, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  kitchen:      { view_orders: true, edit_orders: true, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: false, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: true, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: true, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  chef:         { view_orders: true, edit_orders: true, cancel_orders: false, refund_orders: false, add_menu: true, edit_pricing: true, delete_menu: false, hide_menu: true, view_wallet: false, view_settlements: false, view_reports: true, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: true, approve_purchase: true, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: true, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  reception:    { view_orders: true, edit_orders: false, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: false, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: false, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: false, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  finance:      { view_orders: true, edit_orders: false, cancel_orders: false, refund_orders: true, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: true, view_settlements: true, view_reports: true, add_staff: false, remove_staff: false, edit_salary: true, edit_stock: false, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: false, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: true },
  hr:           { view_orders: false, edit_orders: false, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: true, add_staff: true, remove_staff: true, edit_salary: true, edit_stock: false, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: false, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: true },
  bar:          { view_orders: true, edit_orders: true, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: true, view_wallet: false, view_settlements: false, view_reports: false, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: true, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: true, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  spa:          { view_orders: true, edit_orders: false, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: true, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: true, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: true, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: false },
  housekeeping: { view_orders: true, edit_orders: false, cancel_orders: false, refund_orders: false, add_menu: false, edit_pricing: false, delete_menu: false, hide_menu: false, view_wallet: false, view_settlements: false, view_reports: false, add_staff: false, remove_staff: false, edit_salary: false, edit_stock: false, approve_purchase: false, create_campaigns: false, send_promotions: false, qr_controls: false, nfc_controls: false, printer_settings: false, time_based_access: false, device_based_access: false, branch_wise_access: false, approval_workflows: false, activity_tracking: true },
  franchise:    { view_orders: true, edit_orders: true, cancel_orders: true, refund_orders: true, add_menu: true, edit_pricing: true, delete_menu: true, hide_menu: true, view_wallet: true, view_settlements: true, view_reports: true, add_staff: true, remove_staff: true, edit_salary: true, edit_stock: true, approve_purchase: true, create_campaigns: true, send_promotions: true, qr_controls: true, nfc_controls: true, printer_settings: true, time_based_access: true, device_based_access: true, branch_wise_access: true, approval_workflows: true, activity_tracking: true },
};
