import { Router, type IRouter, type RequestHandler } from "express";
import healthRouter from "./health";
import restaurantAuthRouter from "./restaurant-auth";
import authRouter from "./auth";
import superadminRouter from "./superadmin";
import restaurantsRouter from "./restaurants";
import branchesRouter from "./branches";
import tablesRouter from "./tables";
import menusRouter from "./menus";
import qrcodesRouter from "./qrcodes";
import analyticsRouter from "./analytics";
import ordersRouter from "./orders";
import orderAdjustmentsRouter from "./order-adjustments";
import dayEndRouter from "./day-end";
import attendanceRouter from "./attendance";
import tableOperationsRouter from "./table-operations";
import printingRouter from "./printing";
import staffRouter from "./staff";
import customersRouter from "./customers";
import loyaltyRouter from "./loyalty";
import campaignsRouter from "./campaigns";
import reservationsRouter from "./reservations";
import feedbackRouter from "./feedback";
import waiterCallsRouter from "./waiter_calls";
import publicRouter from "./public";
import publicCustomerRouter from "./public-customer";
import publicSeatingRouter from "./public-seating";
import publicDiningRouter from "./public-dining";
import publicHotelRouter from "./public-hotel";
import publicScanRouter from "./public-scan";
import publicQueueRouter from "./public-queue";
import publicReservationsRouter from "./public-reservations";
import publicEventsRouter from "./public-events";
import publicSpaRouter from "./public-spa";
import publicBarRouter from "./public-bar";
import publicWalletRouter from "./public-wallet";
import publicPaymentsRouter from "./public-payments";
import publicLoyaltyRouter from "./public-loyalty";
import publicAiPersonalizationRouter from "./public-ai-personalization";
import publicAiFutureRouter from "./public-ai-future";
import publicSupportRouter from "./public-support";
import publicLocaleAccessibilityRouter from "./public-locale-accessibility";
import publicOfflineRouter from "./public-offline";
import publicPwaRouter from "./public-pwa";
import publicKioskRouter from "./public-kiosk";
import publicDigitalExperienceRouter from "./public-digital-experience";
import publicSocialReviewRouter from "./public-social-review";
import eventsRouter from "./events";
import banquetEventsRouter from "./banquet-events";
import inventoryRouter from "./inventory";
import foodCostingRouter from "./food-costing";
import procurementRouter from "./procurement";
import financeRouter from "./finance";
import housekeepingRouter from "./housekeeping";
import roomServiceRouter from "./room-service";
import spaRouter from "./spa";
import queueRouter from "./queue";
import notificationsLogRouter from "./notifications-log";
import documentsRouter from "./documents";
import tasksSopRouter from "./tasks-sop";
import auditLogsRouter from "./audit-logs";
import commissionsRouter from "./commissions";
import rbacRouter from "./rbac";
import reviewsRouter from "./reviews";
import digitalSignageRouter from "./digital-signage";
import hardwareRouter from "./hardware";
import corporateRouter from "./corporate";
import backupRouter from "./backup";
import kioskRouter from "./kiosk";
import monitoringRouter from "./monitoring";
import promoCodesRouter from "./promo-codes";
import barAdminRouter from "./bar-admin";
import restaurantPlatformRouter from "./restaurant-platform";
import aiRouter from "./ai";
import mobileKitchenRouter from "./mobile-kitchen";
import appReleasesRouter from "./app-releases";
import featureModulesRouter, {
  registerRestaurantFeatureRoutes,
} from "./feature-modules";
import { requireAuth } from "../middlewares/auth";
import { requireRestaurantSubscription } from "../middlewares/restaurant-subscription.js";
import { requireTenantScope } from "../middlewares/tenant-scope.js";
import { requireStaffPermission } from "../middlewares/staff-permissions.js";
import { enforcePlanLimits } from "../middlewares/plan-limits.js";
import { recordRequest, requestStarted, requestFinished } from "../lib/runtime-metrics.js";

const router: IRouter = Router();

// Every API request is counted here so the monitoring screen can report traffic, errors
// and latency this process actually served. It used to report random numbers.
const countRequest: RequestHandler = (_req, res, next) => {
  const startedAt = Date.now();
  requestStarted();
  res.on("finish", () => {
    requestFinished();
    recordRequest(res.statusCode, Date.now() - startedAt);
  });
  res.on("close", () => { if (!res.writableEnded) requestFinished(); });
  next();
};
router.use(countRequest);

// Ownership is checked once, here, for every path that names a restaurant — so a new
// route is covered the day it is written instead of relying on each one remembering.
router.use(requireTenantScope);
// Then the venue's own role matrix. Tenant scoping keeps one restaurant out of another's
// data; this keeps a waiter out of the finance ledger and the staff list within their own.
router.use(requireStaffPermission);
// A venue may only create what its plan allows. Reading, editing and deleting stay open
// so a venue over its limit can still work with — and reduce — what it already has.
router.use(enforcePlanLimits);
router.use(requireRestaurantSubscription);

router.use(healthRouter);
router.use(featureModulesRouter);
registerRestaurantFeatureRoutes(router, requireAuth);
router.use(restaurantAuthRouter);
router.use(authRouter);
router.use(superadminRouter);
router.use(restaurantsRouter);
router.use(branchesRouter);
router.use(tablesRouter);
router.use(menusRouter);
router.use(qrcodesRouter);
router.use(analyticsRouter);
router.use(ordersRouter);
router.use(orderAdjustmentsRouter);
router.use(dayEndRouter);
router.use(attendanceRouter);
router.use(tableOperationsRouter);
router.use(printingRouter);
router.use(staffRouter);
router.use(customersRouter);
router.use(loyaltyRouter);
router.use(campaignsRouter);
router.use(reservationsRouter);
router.use(feedbackRouter);
router.use(waiterCallsRouter);
router.use(publicRouter);
router.use(publicQueueRouter);
router.use(publicReservationsRouter);
router.use(publicEventsRouter);
router.use(publicSpaRouter);
router.use(publicBarRouter);
router.use(publicWalletRouter);
router.use(publicPaymentsRouter);
router.use(publicLoyaltyRouter);
router.use(publicAiPersonalizationRouter);
router.use(publicAiFutureRouter);
router.use(publicSupportRouter);
router.use(publicLocaleAccessibilityRouter);
router.use(publicOfflineRouter);
router.use(publicPwaRouter);
router.use(publicKioskRouter);
router.use(publicDigitalExperienceRouter);
router.use(publicSocialReviewRouter);
router.use(publicCustomerRouter);
router.use(publicSeatingRouter);
router.use(publicDiningRouter);
router.use(publicHotelRouter);
router.use(publicScanRouter);
router.use(eventsRouter);
router.use(banquetEventsRouter);
router.use(inventoryRouter);
router.use(foodCostingRouter);
router.use(procurementRouter);
router.use(financeRouter);
router.use(housekeepingRouter);
router.use(roomServiceRouter);
router.use(spaRouter);
router.use(queueRouter);
router.use(notificationsLogRouter);
router.use(documentsRouter);
router.use(tasksSopRouter);
router.use(auditLogsRouter);
router.use(commissionsRouter);
router.use(rbacRouter);
router.use(reviewsRouter);
router.use(digitalSignageRouter);
router.use(hardwareRouter);
router.use(corporateRouter);
router.use(backupRouter);
router.use(kioskRouter);
router.use(monitoringRouter);
router.use(promoCodesRouter);
router.use(barAdminRouter);
router.use(restaurantPlatformRouter);
router.use(aiRouter);
router.use(appReleasesRouter);
router.use("/v1", mobileKitchenRouter);

export default router;
