import '../state/kitchen_command_controller.dart';

/// Maps command-center nav indices to controller refresh + loading state.
class ModuleRefreshRegistry {
  const ModuleRefreshRegistry._();

  static Future<void> refresh(
    KitchenCommandController controller,
    int navIndex,
  ) {
    return switch (navIndex) {
      0 => controller.refreshDashboard(),
      1 => controller.refreshKds(),
      2 => controller.refreshSections(),
      3 => controller.refreshProcessing(),
      4 => controller.refreshFiring(),
      5 => controller.refreshPrep(),
      6 => controller.refreshModifiers(),
      7 => controller.refreshChefTasks(),
      8 => Future.wait([
          controller.refreshChefTasks(),
          controller.refreshStaffPerformance(),
          controller.refreshStaffWellness(),
        ]),
      9 => controller.refreshSafety(),
      10 => controller.refreshAiAssistant(),
      11 => controller.refreshOrderPriority(),
      12 => controller.refreshKitchenCommunication(),
      13 => controller.refreshInventory(),
      14 => controller.refreshRecipeCosting(),
      15 => controller.refreshPrepStations(),
      16 => controller.refreshBatchCooking(),
      17 => controller.refreshDelayEscalation(),
      18 => controller.refreshQualityControl(),
      19 => controller.refreshCustomerReturn(),
      20 => controller.refreshExpeditor(),
      21 => controller.refreshPacking(),
      22 => controller.refreshDeliveryAggregator(),
      23 => controller.refreshBarBeverage(),
      24 => controller.refreshBakeryDessert(),
      25 => controller.refreshCloudKitchen(),
      26 => controller.refreshBanquet(),
      27 => controller.refreshRoomService(),
      28 => controller.refreshCleaningHygiene(),
      29 => controller.refreshEquipment(),
      30 => controller.refreshSmartEnergy(),
      31 => controller.refreshIotDevice(),
      32 => controller.refreshStaffPerformance(),
      33 => controller.refreshStaffShift(),
      34 => controller.refreshStaffWellness(),
      35 => controller.refreshLiveAlerts(),
      36 => controller.refreshPanicEmergency(),
      37 => controller.refreshOfflineFailover(),
      38 => controller.refreshAnalyticsReporting(),
      39 => controller.refreshKitchenHeatmap(),
      40 => controller.refreshHardwareIntegration(),
      41 => controller.refreshSmartwatchSupport(),
      42 => controller.refreshMultiBranch(),
      43 => controller.refreshAuditCompliance(),
      44 => controller.refreshBackupRecovery(),
      45 => controller.refreshSandboxTraining(),
      46 => controller.refreshHiddenEnterprise(),
      47 => controller.refreshFutureAiExpansion(),
      48 => controller.refreshWaiterAutoAssignment(),
      49 => controller.refreshDashboard(),
      _ => controller.refreshDashboard(),
    };
  }

  static bool isLoading(KitchenCommandController controller, int navIndex) {
    return switch (navIndex) {
      0 => controller.loading,
      1 => controller.kdsLoading,
      2 => controller.sectionsLoading,
      3 => controller.processingLoading,
      4 => controller.firingLoading,
      5 => controller.prepLoading,
      6 => controller.modifierLoading,
      7 => controller.chefTaskLoading,
      8 =>
        controller.chefTaskLoading ||
            controller.staffPerformanceLoading ||
            controller.staffWellnessLoading,
      9 => controller.safetyLoading,
      10 => controller.aiLoading,
      11 => controller.priorityLoading,
      12 => controller.communicationLoading,
      13 => controller.inventoryLoading,
      14 => controller.recipeCostingLoading,
      15 => controller.prepStationLoading,
      16 => controller.batchCookingLoading,
      17 => controller.delayEscalationLoading,
      18 => controller.qualityControlLoading,
      19 => controller.customerReturnLoading,
      20 => controller.expeditorLoading,
      21 => controller.packingLoading,
      22 => controller.deliveryAggregatorLoading,
      23 => controller.barBeverageLoading,
      24 => controller.bakeryDessertLoading,
      25 => controller.cloudKitchenLoading,
      26 => controller.banquetLoading,
      27 => controller.roomServiceLoading,
      28 => controller.cleaningHygieneLoading,
      29 => controller.equipmentLoading,
      30 => controller.smartEnergyLoading,
      31 => controller.iotDeviceLoading,
      32 => controller.staffPerformanceLoading,
      33 => controller.staffShiftLoading,
      34 => controller.staffWellnessLoading,
      35 => controller.liveAlertLoading,
      36 => controller.panicEmergencyLoading,
      37 => controller.offlineFailoverLoading,
      38 => controller.analyticsReportingLoading,
      39 => controller.kitchenHeatmapLoading,
      40 => controller.hardwareIntegrationLoading,
      41 => controller.smartwatchSupportLoading,
      42 => controller.multiBranchLoading,
      43 => controller.auditComplianceLoading,
      44 => controller.backupRecoveryLoading,
      45 => controller.sandboxTrainingLoading,
      46 => controller.hiddenEnterpriseLoading,
      47 => controller.futureAiExpansionLoading,
      48 => controller.waiterAutoAssignmentLoading,
      49 => controller.refreshing,
      _ => controller.refreshing,
    };
  }
}
